// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Socios.Infrastructure.Context;

#nullable disable

namespace Socios.Infrastructure.Migrations
{
    [DbContext(typeof(SociosDbContext))]
    [Migration("20260805232019_SeedUpper")]
    partial class SeedUpper
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Socios.Domain.Entities.Caja", b =>
                {
                    b.Property<int>("Id_Movimiento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Movimiento"));

                    b.Property<DateTime>("FechaHoraMov")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id_CajaDiaria")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Cuenta")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Detmov")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Entidad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tipo_Movimiento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id_Movimiento");

                    b.HasIndex("Id_CajaDiaria");

                    b.HasIndex("Id_Cuenta");

                    b.HasIndex("Id_Detmov");

                    b.HasIndex("Id_Entidad");

                    b.HasIndex("Id_MetodoPago");

                    b.ToTable("caja", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Movimiento = 1,
                            FechaHoraMov = new DateTime(2026, 6, 10, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            Id_CajaDiaria = 1,
                            Id_Cuenta = 1,
                            Id_Detmov = 1,
                            Id_Entidad = 1,
                            Id_MetodoPago = 2,
                            Monto = 13500m,
                            Observacion = "PAGO CUOTA MAYO",
                            Tipo_Movimiento = "INGRESO"
                        },
                        new
                        {
                            Id_Movimiento = 2,
                            FechaHoraMov = new DateTime(2026, 6, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Id_CajaDiaria = 1,
                            Id_Cuenta = 2,
                            Id_Detmov = 5,
                            Id_Entidad = 3,
                            Id_MetodoPago = 1,
                            Monto = 42500.47m,
                            Observacion = "PAGO GAS MES JUNIO",
                            Tipo_Movimiento = "EGRESO"
                        },
                        new
                        {
                            Id_Movimiento = 3,
                            FechaHoraMov = new DateTime(2026, 6, 10, 9, 30, 0, 0, DateTimeKind.Unspecified),
                            Id_CajaDiaria = 2,
                            Id_Cuenta = 2,
                            Id_Detmov = 4,
                            Id_Entidad = 4,
                            Id_MetodoPago = 1,
                            Monto = 30000m,
                            Observacion = "COLABORACIÓN PODOLOGÍA",
                            Tipo_Movimiento = "INGRESO"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.CierreContable", b =>
                {
                    b.Property<int>("Id_Cierre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Cierre"));

                    b.Property<int?>("Anio_Periodo")
                        .HasColumnType("int");

                    b.Property<DateTime>("Fechor")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<int?>("Mes_Periodo")
                        .HasColumnType("int");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id_Cierre");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("cierres_contables", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Cierre = 1,
                            Anio_Periodo = 2026,
                            Fechor = new DateTime(2026, 3, 31, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Usuario = 3,
                            Mes_Periodo = 3,
                            Tipo = "MENSUAL"
                        },
                        new
                        {
                            Id_Cierre = 2,
                            Anio_Periodo = 2025,
                            Fechor = new DateTime(2026, 1, 10, 8, 30, 0, 0, DateTimeKind.Unspecified),
                            Id_Usuario = 2,
                            Tipo = "ANUAL"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Ciudad", b =>
                {
                    b.Property<int>("Id_Ciudad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Ciudad"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id_Ciudad");

                    b.ToTable("ciudades", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Ciudad = 1,
                            Nombre = "ROLDÁN"
                        },
                        new
                        {
                            Id_Ciudad = 2,
                            Nombre = "FUNES"
                        },
                        new
                        {
                            Id_Ciudad = 3,
                            Nombre = "ROSARIO"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Codeudor", b =>
                {
                    b.Property<int>("Id_Codeudor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Codeudor"));

                    b.Property<int?>("EntidadCodeudorId_Entidad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Entidad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_EntidadCodeudor")
                        .HasColumnType("integer");

                    b.HasKey("Id_Codeudor");

                    b.HasIndex("EntidadCodeudorId_Entidad");

                    b.HasIndex("Id_EntidadCodeudor");

                    b.ToTable("codeudores", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Codeudor = 1,
                            Id_Entidad = 2,
                            Id_EntidadCodeudor = 1
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Colaborador", b =>
                {
                    b.Property<int>("Id_Colaborador")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Colaborador"));

                    b.Property<int>("Id_Entidad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Prestacion")
                        .HasColumnType("integer");

                    b.HasKey("Id_Colaborador");

                    b.HasIndex("Id_Entidad");

                    b.HasIndex("Id_Prestacion");

                    b.ToTable("colaboradores", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Colaborador = 1,
                            Id_Entidad = 4,
                            Id_Prestacion = 2
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Contacto", b =>
                {
                    b.Property<int>("Id_Contacto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Contacto"));

                    b.Property<string>("ContactoEntidad")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<int>("Id_Entidad")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_Contacto");

                    b.HasIndex("Id_Entidad");

                    b.ToTable("contactos", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Contacto = 1,
                            ContactoEntidad = "3413458966",
                            Id_Entidad = 1,
                            Tipo = "TELÉFONO"
                        },
                        new
                        {
                            Id_Contacto = 2,
                            ContactoEntidad = "luciano@gmail",
                            Id_Entidad = 1,
                            Tipo = "MAIL"
                        },
                        new
                        {
                            Id_Contacto = 3,
                            ContactoEntidad = "3413485977",
                            Id_Entidad = 4,
                            Tipo = "TELÉFONO"
                        },
                        new
                        {
                            Id_Contacto = 4,
                            ContactoEntidad = "08007775427",
                            Id_Entidad = 3,
                            Tipo = "TELÉFONO"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Cuenta", b =>
                {
                    b.Property<int>("Id_Cuenta")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Cuenta"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("NombreCuenta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("NroCuenta")
                        .HasColumnType("integer");

                    b.HasKey("Id_Cuenta");

                    b.ToTable("cuentas", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Cuenta = 1,
                            Estado = "ACTIVA",
                            NombreCuenta = "EFECTIVO",
                            NroCuenta = 0
                        },
                        new
                        {
                            Id_Cuenta = 2,
                            Estado = "ACTIVA",
                            NombreCuenta = "BANCO MACRO",
                            NroCuenta = 789012
                        },
                        new
                        {
                            Id_Cuenta = 3,
                            Estado = "INACTIVA",
                            NombreCuenta = "BANCO NACION",
                            NroCuenta = 712906
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Cuota", b =>
                {
                    b.Property<int>("Id_Deuda")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Deuda"));

                    b.Property<int>("Anio_Periodo")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("FechaHoraGeneracion")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaVencimiento")
                        .HasColumnType("date");

                    b.Property<int>("Id_Entidad")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_Movimiento")
                        .HasColumnType("integer");

                    b.Property<int>("Id_TipoCuota")
                        .HasColumnType("integer");

                    b.Property<int>("Mes_Periodo")
                        .HasColumnType("int");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id_Deuda");

                    b.HasIndex("Id_Entidad");

                    b.HasIndex("Id_Movimiento");

                    b.HasIndex("Id_TipoCuota");

                    b.ToTable("cuotas", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Deuda = 1,
                            Anio_Periodo = 2026,
                            Estado = "PAGADO",
                            FechaHoraGeneracion = new DateTime(2026, 6, 10, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 1,
                            Id_TipoCuota = 1,
                            Mes_Periodo = 6,
                            Monto = 4500m
                        },
                        new
                        {
                            Id_Deuda = 2,
                            Anio_Periodo = 2026,
                            Estado = "PENDIENTE",
                            FechaHoraGeneracion = new DateTime(2026, 6, 27, 8, 20, 0, 0, DateTimeKind.Unspecified),
                            FechaVencimiento = new DateTime(2026, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 1,
                            Id_TipoCuota = 1,
                            Mes_Periodo = 7,
                            Monto = 4500m
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.DetalleMovimiento", b =>
                {
                    b.Property<int>("Id_Detmov")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Detmov"));

                    b.Property<string>("NombreDetalleMovimiento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id_Detmov");

                    b.ToTable("detalle_movimientos", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Detmov = 1,
                            NombreDetalleMovimiento = "CUOTA SOCIO"
                        },
                        new
                        {
                            Id_Detmov = 2,
                            NombreDetalleMovimiento = "CUOTA SEPELIO"
                        },
                        new
                        {
                            Id_Detmov = 3,
                            NombreDetalleMovimiento = "AJUSTE DIFERENCIA CAJA"
                        },
                        new
                        {
                            Id_Detmov = 4,
                            NombreDetalleMovimiento = "COLABORACIÓN"
                        },
                        new
                        {
                            Id_Detmov = 5,
                            NombreDetalleMovimiento = "PAGO A PROVEEDOR"
                        },
                        new
                        {
                            Id_Detmov = 6,
                            NombreDetalleMovimiento = "TRANSFERENCIA"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Entidad", b =>
                {
                    b.Property<int>("Id_Entidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Entidad"));

                    b.Property<int?>("Altura")
                        .HasColumnType("integer");

                    b.Property<string>("Apellido")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Calle")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("CuitCuil")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Dni")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Id_Ciudad")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Nacimiento")
                        .HasColumnType("date");

                    b.Property<string>("Nombre")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observacion")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RazonSocial")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Sexo")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_Entidad");

                    b.HasIndex("Dni")
                        .IsUnique();

                    b.HasIndex("Id_Ciudad");

                    b.ToTable("entidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Entidad = 1,
                            Altura = 250,
                            Apellido = "OLDAN",
                            Calle = "INDEPENDENCIA",
                            CuitCuil = "20321270574",
                            Dni = "32127057",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1959, 7, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "LUCIANO",
                            Sexo = "HOMBRE",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 2,
                            Altura = 458,
                            Apellido = "PÉREZ",
                            Calle = "GALINDO",
                            Dni = "32185166",
                            Id_Ciudad = 2,
                            Nacimiento = new DateTime(1998, 3, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "JUAN",
                            Sexo = "HOMBRE",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 3,
                            Altura = 166,
                            Calle = "MITRE",
                            CuitCuil = "30657866330",
                            Id_Ciudad = 3,
                            Nacimiento = new DateTime(1980, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            RazonSocial = "LITORAL GAS S.A",
                            Sexo = "PERSONA JURIDICA",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 4,
                            Altura = 347,
                            Apellido = "LÓPEZ",
                            Calle = "LAS HERAS",
                            Dni = "55406681",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1987, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "MARÍA",
                            Sexo = "MUJER",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 5,
                            Altura = 417,
                            Apellido = "AVILA",
                            Calle = "SALTA",
                            Dni = "6166108",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1958, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "EDUARDO",
                            Sexo = "HOMBRE",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 6,
                            Altura = 270,
                            Apellido = "MASABEU",
                            Calle = "INDEPENDENCIA",
                            Dni = "6164804",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1960, 7, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "RUTILIO ALFREDO",
                            Sexo = "HOMBRE",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 7,
                            Altura = 684,
                            Apellido = "MASABEU",
                            Calle = "MENDOZA",
                            Dni = "14658096",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1955, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "ALFREDO",
                            Sexo = "HOMBRE",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 8,
                            Altura = 867,
                            Apellido = "MEYADO",
                            Calle = "CORRIENTES",
                            Dni = "4989850",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1962, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "JOSÉ MOISÉS",
                            Sexo = "HOMBRE",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 9,
                            Altura = 1044,
                            Apellido = "IPPOLITI",
                            Calle = "MENDOZA",
                            Dni = "6176088",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1959, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "HUGO",
                            Sexo = "HOMBRE",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 10,
                            Altura = 417,
                            Apellido = "FLORIÁN DE AVILA",
                            Calle = "SALTA",
                            Dni = "3247480",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1961, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "SUSANA",
                            Sexo = "MUJER",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 11,
                            Altura = 292,
                            Apellido = "HERRERA",
                            Calle = "1 DE MAYO",
                            Dni = "3962438",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1956, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "LUCY",
                            Sexo = "MUJER",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 12,
                            Altura = 369,
                            Apellido = "MURATTURE",
                            Calle = "MITRE",
                            Dni = "4105793",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1957, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "IRIS A.",
                            Sexo = "MUJER",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 13,
                            Altura = 455,
                            Apellido = "VILLAREAL",
                            Calle = "JUJUY",
                            Dni = "12266301",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1963, 4, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "RAQUEL",
                            Sexo = "MUJER",
                            Tipo = "DNI"
                        },
                        new
                        {
                            Id_Entidad = 14,
                            Altura = 953,
                            Apellido = "BRAVO DE PONTI",
                            Calle = "JUJUY",
                            Dni = "4645560",
                            Id_Ciudad = 1,
                            Nacimiento = new DateTime(1964, 10, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "ANA MARÍA",
                            Sexo = "MUJER",
                            Tipo = "DNI"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.EntidadBaja", b =>
                {
                    b.Property<int>("Id_Baja")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Baja"));

                    b.Property<DateTime>("Fecha_Baja")
                        .HasColumnType("date");

                    b.Property<int>("Id_EntidadTipo")
                        .HasColumnType("integer");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.HasKey("Id_Baja");

                    b.HasIndex("Id_EntidadTipo");

                    b.ToTable("entidad_bajas", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Baja = 1,
                            Fecha_Baja = new DateTime(2016, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_EntidadTipo = 1,
                            Motivo = "MORA"
                        },
                        new
                        {
                            Id_Baja = 2,
                            Fecha_Baja = new DateTime(2015, 12, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_EntidadTipo = 3,
                            Motivo = "RENUNCIA"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.EntidadTipo", b =>
                {
                    b.Property<int>("Id_EntidadTipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_EntidadTipo"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Fecha_Alta")
                        .HasColumnType("date");

                    b.Property<int>("Id_Entidad")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id_EntidadTipo");

                    b.HasIndex("Id_Entidad");

                    b.HasIndex("Id_Tipo");

                    b.ToTable("entidad_tipos", (string)null);

                    b.HasData(
                        new
                        {
                            Id_EntidadTipo = 1,
                            Estado = "INACTIVO",
                            Fecha_Alta = new DateTime(1995, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 1,
                            Id_Tipo = 1
                        },
                        new
                        {
                            Id_EntidadTipo = 2,
                            Estado = "ACTIVO",
                            Fecha_Alta = new DateTime(2000, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 1,
                            Id_Tipo = 3
                        },
                        new
                        {
                            Id_EntidadTipo = 3,
                            Estado = "INACTIVO",
                            Fecha_Alta = new DateTime(2008, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 4,
                            Id_Tipo = 3
                        },
                        new
                        {
                            Id_EntidadTipo = 4,
                            Estado = "ACTIVO",
                            Fecha_Alta = new DateTime(1995, 1, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 5,
                            Id_Tipo = 1
                        },
                        new
                        {
                            Id_EntidadTipo = 5,
                            Estado = "ACTIVO",
                            Fecha_Alta = new DateTime(2020, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 6,
                            Id_Tipo = 1
                        },
                        new
                        {
                            Id_EntidadTipo = 6,
                            Estado = "ACTIVO",
                            Fecha_Alta = new DateTime(2021, 7, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 7,
                            Id_Tipo = 1
                        },
                        new
                        {
                            Id_EntidadTipo = 7,
                            Estado = "INACTIVO",
                            Fecha_Alta = new DateTime(2022, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 8,
                            Id_Tipo = 1
                        },
                        new
                        {
                            Id_EntidadTipo = 8,
                            Estado = "ACTIVO",
                            Fecha_Alta = new DateTime(2023, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 9,
                            Id_Tipo = 1
                        },
                        new
                        {
                            Id_EntidadTipo = 9,
                            Estado = "ACTIVO",
                            Fecha_Alta = new DateTime(2024, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 10,
                            Id_Tipo = 1
                        },
                        new
                        {
                            Id_EntidadTipo = 10,
                            Estado = "ACTIVO",
                            Fecha_Alta = new DateTime(2020, 9, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 11,
                            Id_Tipo = 1
                        },
                        new
                        {
                            Id_EntidadTipo = 11,
                            Estado = "INACTIVO",
                            Fecha_Alta = new DateTime(2021, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 12,
                            Id_Tipo = 1
                        },
                        new
                        {
                            Id_EntidadTipo = 12,
                            Estado = "ACTIVO",
                            Fecha_Alta = new DateTime(2022, 4, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 13,
                            Id_Tipo = 1
                        },
                        new
                        {
                            Id_EntidadTipo = 13,
                            Estado = "ACTIVO",
                            Fecha_Alta = new DateTime(2025, 2, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Entidad = 14,
                            Id_Tipo = 1
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.EstadoCajaDiaria", b =>
                {
                    b.Property<int>("Id_CajaDiaria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_CajaDiaria"));

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("Id_Usuario")
                        .HasColumnType("integer");

                    b.Property<int>("Nro_Caja")
                        .HasColumnType("integer");

                    b.Property<decimal>("Saldo")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id_CajaDiaria");

                    b.HasIndex("Id_Usuario");

                    b.ToTable("estado_cajadiaria", (string)null);

                    b.HasData(
                        new
                        {
                            Id_CajaDiaria = 1,
                            FechaHora = new DateTime(2026, 6, 9, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            Id_Usuario = 1,
                            Nro_Caja = 1,
                            Saldo = 100000m,
                            Tipo = "APERTURA"
                        },
                        new
                        {
                            Id_CajaDiaria = 2,
                            FechaHora = new DateTime(2026, 6, 9, 12, 5, 0, 0, DateTimeKind.Unspecified),
                            Id_Usuario = 1,
                            Nro_Caja = 1,
                            Saldo = 142000m,
                            Tipo = "CIERRE"
                        },
                        new
                        {
                            Id_CajaDiaria = 3,
                            FechaHora = new DateTime(2026, 6, 9, 8, 10, 0, 0, DateTimeKind.Unspecified),
                            Id_Usuario = 2,
                            Nro_Caja = 2,
                            Saldo = 78000m,
                            Tipo = "APERTURA"
                        },
                        new
                        {
                            Id_CajaDiaria = 4,
                            FechaHora = new DateTime(2026, 6, 9, 12, 15, 0, 0, DateTimeKind.Unspecified),
                            Id_Usuario = 2,
                            Nro_Caja = 2,
                            Saldo = 250000m,
                            Tipo = "CIERRE"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.MetodoPago", b =>
                {
                    b.Property<int>("Id_MetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_MetodoPago"));

                    b.Property<string>("NombreMetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_MetodoPago");

                    b.ToTable("metodos_pago", (string)null);

                    b.HasData(
                        new
                        {
                            Id_MetodoPago = 1,
                            NombreMetodoPago = "EFECTIVO"
                        },
                        new
                        {
                            Id_MetodoPago = 2,
                            NombreMetodoPago = "TRANSFERENCIA BANCARIA"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.MovimientoPrestacion", b =>
                {
                    b.Property<int>("Id_MovimientoPrestacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_MovimientoPrestacion"));

                    b.Property<int>("Id_Movimiento")
                        .HasColumnType("integer");

                    b.Property<int>("Id_Prestacion")
                        .HasColumnType("integer");

                    b.HasKey("Id_MovimientoPrestacion");

                    b.HasIndex("Id_Movimiento");

                    b.HasIndex("Id_Prestacion");

                    b.ToTable("movimientos_prestaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id_MovimientoPrestacion = 1,
                            Id_Movimiento = 3,
                            Id_Prestacion = 1
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Nicho", b =>
                {
                    b.Property<int>("Id_Nicho")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Nicho"));

                    b.Property<string>("ConLapida")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<int?>("Cuotas")
                        .HasColumnType("int");

                    b.Property<int?>("Id_Entidad")
                        .HasColumnType("integer");

                    b.Property<decimal?>("InteresMensual")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("NroNicho")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Ocupado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Sector")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal?>("ValorLapida")
                        .HasColumnType("numeric");

                    b.Property<decimal>("ValorNicho")
                        .HasColumnType("numeric");

                    b.HasKey("Id_Nicho");

                    b.HasIndex("Id_Entidad");

                    b.ToTable("nichos", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Nicho = 1,
                            ConLapida = "SI",
                            Cuotas = 2,
                            Id_Entidad = 1,
                            InteresMensual = 2.5m,
                            NroNicho = "8",
                            Ocupado = "SI",
                            Sector = "A",
                            ValorLapida = 50000m,
                            ValorNicho = 2500000m
                        },
                        new
                        {
                            Id_Nicho = 2,
                            ConLapida = "NO",
                            NroNicho = "1",
                            Ocupado = "NO",
                            Sector = "B",
                            ValorNicho = 2500000m
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.ObraSocial", b =>
                {
                    b.Property<int>("Id_ObraSocial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_ObraSocial"));

                    b.Property<string>("NombreObraSocial")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id_ObraSocial");

                    b.ToTable("obras_sociales", (string)null);

                    b.HasData(
                        new
                        {
                            Id_ObraSocial = 1,
                            NombreObraSocial = "PAMI"
                        },
                        new
                        {
                            Id_ObraSocial = 2,
                            NombreObraSocial = "OSDE"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Prestacion", b =>
                {
                    b.Property<int>("Id_Prestacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Prestacion"));

                    b.Property<string>("NombrePrestacion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id_Prestacion");

                    b.ToTable("prestaciones", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Prestacion = 1,
                            NombrePrestacion = "PODOLOGÍA"
                        },
                        new
                        {
                            Id_Prestacion = 2,
                            NombrePrestacion = "CARDIOLOGÍA"
                        },
                        new
                        {
                            Id_Prestacion = 3,
                            NombrePrestacion = "ALQUILER SALÓN"
                        },
                        new
                        {
                            Id_Prestacion = 4,
                            NombrePrestacion = "COMISIÓN COBRADOR"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("Id_Rol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Rol"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RolNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id_Rol");

                    b.ToTable("roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Rol = 1,
                            Descripcion = "SECRETARIA QUE MANEJA TODO EL SISTEMA",
                            RolNombre = "SECRETARIA"
                        },
                        new
                        {
                            Id_Rol = 2,
                            Descripcion = "SOLO POSEE ACCESO AL MÓDULO DE INFORMES",
                            RolNombre = "CONSULTOR"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Socio", b =>
                {
                    b.Property<int>("Id_Socio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Socio"));

                    b.Property<string>("Cobrador")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Id_Entidad")
                        .HasColumnType("integer");

                    b.Property<int?>("Id_OS")
                        .HasColumnType("integer");

                    b.Property<string>("Numero_Afiliado")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Plan")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sepelio")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.HasKey("Id_Socio");

                    b.HasIndex("Id_Entidad");

                    b.HasIndex("Id_OS");

                    b.ToTable("socios", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Socio = 1,
                            Cobrador = "NO",
                            Id_Entidad = 1,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "A",
                            Sepelio = "SI"
                        },
                        new
                        {
                            Id_Socio = 4,
                            Cobrador = "NO",
                            Id_Entidad = 5,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "A",
                            Sepelio = "SI"
                        },
                        new
                        {
                            Id_Socio = 5,
                            Cobrador = "SI",
                            Id_Entidad = 6,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "B",
                            Sepelio = "NO"
                        },
                        new
                        {
                            Id_Socio = 6,
                            Cobrador = "NO",
                            Id_Entidad = 7,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "A",
                            Sepelio = "NO"
                        },
                        new
                        {
                            Id_Socio = 7,
                            Cobrador = "SI",
                            Id_Entidad = 8,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "B",
                            Sepelio = "SI"
                        },
                        new
                        {
                            Id_Socio = 8,
                            Cobrador = "SI",
                            Id_Entidad = 9,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "A",
                            Sepelio = "SI"
                        },
                        new
                        {
                            Id_Socio = 9,
                            Cobrador = "NO",
                            Id_Entidad = 10,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "B",
                            Sepelio = "NO"
                        },
                        new
                        {
                            Id_Socio = 10,
                            Cobrador = "SI",
                            Id_Entidad = 11,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "A",
                            Sepelio = "NO"
                        },
                        new
                        {
                            Id_Socio = 11,
                            Cobrador = "NO",
                            Id_Entidad = 12,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "B",
                            Sepelio = "SI"
                        },
                        new
                        {
                            Id_Socio = 12,
                            Cobrador = "NO",
                            Id_Entidad = 13,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "A",
                            Sepelio = "SI"
                        },
                        new
                        {
                            Id_Socio = 13,
                            Cobrador = "SI",
                            Id_Entidad = 14,
                            Id_OS = 1,
                            Numero_Afiliado = "",
                            Plan = "B",
                            Sepelio = "NO"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.TipoCuota", b =>
                {
                    b.Property<int>("Id_TipoCuota")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_TipoCuota"));

                    b.Property<string>("Concepto")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("Fecha_ultimamodif")
                        .HasColumnType("timestamp without time zone");

                    b.Property<decimal>("Importe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Tiene_EdadTope")
                        .HasColumnType("boolean");

                    b.HasKey("Id_TipoCuota");

                    b.ToTable("tipo_cuotas", (string)null);

                    b.HasData(
                        new
                        {
                            Id_TipoCuota = 1,
                            Concepto = "SOCIO",
                            Fecha_ultimamodif = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 4500m,
                            Tiene_EdadTope = true
                        },
                        new
                        {
                            Id_TipoCuota = 2,
                            Concepto = "SEPELIO",
                            Fecha_ultimamodif = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 10000m,
                            Tiene_EdadTope = true
                        },
                        new
                        {
                            Id_TipoCuota = 3,
                            Concepto = "SEPELIO",
                            Fecha_ultimamodif = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 12000m,
                            Tiene_EdadTope = true
                        },
                        new
                        {
                            Id_TipoCuota = 4,
                            Concepto = "SEPELIO",
                            Fecha_ultimamodif = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 12000m,
                            Tiene_EdadTope = false
                        },
                        new
                        {
                            Id_TipoCuota = 5,
                            Concepto = "SEPELIO",
                            Fecha_ultimamodif = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 14000m,
                            Tiene_EdadTope = false
                        },
                        new
                        {
                            Id_TipoCuota = 6,
                            Concepto = "NICHO",
                            Fecha_ultimamodif = new DateTime(2026, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Importe = 300000m,
                            Tiene_EdadTope = false
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.TipoEntidad", b =>
                {
                    b.Property<int>("Id_Tipo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Tipo"));

                    b.Property<string>("NombreTipoEntidad")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id_Tipo");

                    b.ToTable("tipo_entidades", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Tipo = 1,
                            NombreTipoEntidad = "SOCIO"
                        },
                        new
                        {
                            Id_Tipo = 2,
                            NombreTipoEntidad = "PROVEEDOR"
                        },
                        new
                        {
                            Id_Tipo = 3,
                            NombreTipoEntidad = "COLABORADOR"
                        },
                        new
                        {
                            Id_Tipo = 4,
                            NombreTipoEntidad = "EMPLEADO"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.TipoPlan", b =>
                {
                    b.Property<int>("Id_TipoPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_TipoPlan"));

                    b.Property<int?>("EdadTope")
                        .HasColumnType("integer");

                    b.Property<int>("Id_TipoCuota")
                        .HasColumnType("integer");

                    b.Property<string>("Tipo_Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id_TipoPlan");

                    b.HasIndex("Id_TipoCuota");

                    b.ToTable("tipo_planes", (string)null);

                    b.HasData(
                        new
                        {
                            Id_TipoPlan = 1,
                            EdadTope = 65,
                            Id_TipoCuota = 2,
                            Tipo_Plan = "A"
                        },
                        new
                        {
                            Id_TipoPlan = 2,
                            EdadTope = 65,
                            Id_TipoCuota = 3,
                            Tipo_Plan = "B"
                        },
                        new
                        {
                            Id_TipoPlan = 3,
                            Id_TipoCuota = 4,
                            Tipo_Plan = "A"
                        },
                        new
                        {
                            Id_TipoPlan = 4,
                            Id_TipoCuota = 5,
                            Tipo_Plan = "B"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id_Usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id_Usuario"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("Id_Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UsuarioNombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id_Usuario");

                    b.HasIndex("Id_Rol");

                    b.ToTable("usuarios", (string)null);

                    b.HasData(
                        new
                        {
                            Id_Usuario = 1,
                            Estado = "Activo",
                            Id_Rol = 2,
                            Password = "$2a$11$5.O9NB.FFBZ98GrE24jq7et8c0ACOkRVsSueihm78or/JNZmjVGay",
                            UsuarioNombre = "CJR"
                        },
                        new
                        {
                            Id_Usuario = 2,
                            Estado = "Activo",
                            Id_Rol = 1,
                            Password = "$2a$11$5.O9NB.FFBZ98GrE24jq7et8c0ACOkRVsSueihm78or/JNZmjVGay",
                            UsuarioNombre = "ADRIANA"
                        },
                        new
                        {
                            Id_Usuario = 3,
                            Estado = "Activo",
                            Id_Rol = 1,
                            Password = "$2a$11$5.O9NB.FFBZ98GrE24jq7et8c0ACOkRVsSueihm78or/JNZmjVGay",
                            UsuarioNombre = "MARCELA"
                        });
                });

            modelBuilder.Entity("Socios.Domain.Entities.Caja", b =>
                {
                    b.HasOne("Socios.Domain.Entities.EstadoCajaDiaria", "EstadoCajaDiaria")
                        .WithMany()
                        .HasForeignKey("Id_CajaDiaria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Socios.Domain.Entities.Cuenta", "Cuenta")
                        .WithMany()
                        .HasForeignKey("Id_Cuenta")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Socios.Domain.Entities.DetalleMovimiento", "DetalleMovimiento")
                        .WithMany()
                        .HasForeignKey("Id_Detmov")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Socios.Domain.Entities.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("Id_Entidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Socios.Domain.Entities.MetodoPago", "MetodoPago")
                        .WithMany()
                        .HasForeignKey("Id_MetodoPago")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cuenta");

                    b.Navigation("DetalleMovimiento");

                    b.Navigation("Entidad");

                    b.Navigation("EstadoCajaDiaria");

                    b.Navigation("MetodoPago");
                });

            modelBuilder.Entity("Socios.Domain.Entities.CierreContable", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Socios.Domain.Entities.Codeudor", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Entidad", "EntidadCodeudor")
                        .WithMany()
                        .HasForeignKey("EntidadCodeudorId_Entidad");

                    b.HasOne("Socios.Domain.Entities.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("Id_EntidadCodeudor")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entidad");

                    b.Navigation("EntidadCodeudor");
                });

            modelBuilder.Entity("Socios.Domain.Entities.Colaborador", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("Id_Entidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Socios.Domain.Entities.Prestacion", "Prestacion")
                        .WithMany()
                        .HasForeignKey("Id_Prestacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entidad");

                    b.Navigation("Prestacion");
                });

            modelBuilder.Entity("Socios.Domain.Entities.Contacto", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("Id_Entidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entidad");
                });

            modelBuilder.Entity("Socios.Domain.Entities.Cuota", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("Id_Entidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Socios.Domain.Entities.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("Id_Movimiento")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Socios.Domain.Entities.TipoCuota", "TipoCuota")
                        .WithMany()
                        .HasForeignKey("Id_TipoCuota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Entidad");

                    b.Navigation("TipoCuota");
                });

            modelBuilder.Entity("Socios.Domain.Entities.Entidad", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Ciudad", "Ciudad")
                        .WithMany()
                        .HasForeignKey("Id_Ciudad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ciudad");
                });

            modelBuilder.Entity("Socios.Domain.Entities.EntidadBaja", b =>
                {
                    b.HasOne("Socios.Domain.Entities.EntidadTipo", "EntidadTipo")
                        .WithMany()
                        .HasForeignKey("Id_EntidadTipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EntidadTipo");
                });

            modelBuilder.Entity("Socios.Domain.Entities.EntidadTipo", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("Id_Entidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Socios.Domain.Entities.TipoEntidad", "TipoEntidad")
                        .WithMany()
                        .HasForeignKey("Id_Tipo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Entidad");

                    b.Navigation("TipoEntidad");
                });

            modelBuilder.Entity("Socios.Domain.Entities.EstadoCajaDiaria", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("Id_Usuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Socios.Domain.Entities.MovimientoPrestacion", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Caja", "Caja")
                        .WithMany()
                        .HasForeignKey("Id_Movimiento")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Socios.Domain.Entities.Prestacion", "Prestacion")
                        .WithMany()
                        .HasForeignKey("Id_Prestacion")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Caja");

                    b.Navigation("Prestacion");
                });

            modelBuilder.Entity("Socios.Domain.Entities.Nicho", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("Id_Entidad")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Entidad");
                });

            modelBuilder.Entity("Socios.Domain.Entities.Socio", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Entidad", "Entidad")
                        .WithMany()
                        .HasForeignKey("Id_Entidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Socios.Domain.Entities.ObraSocial", "ObraSocial")
                        .WithMany()
                        .HasForeignKey("Id_OS")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Entidad");

                    b.Navigation("ObraSocial");
                });

            modelBuilder.Entity("Socios.Domain.Entities.TipoPlan", b =>
                {
                    b.HasOne("Socios.Domain.Entities.TipoCuota", "TipoCuota")
                        .WithMany()
                        .HasForeignKey("Id_TipoCuota")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TipoCuota");
                });

            modelBuilder.Entity("Socios.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("Socios.Domain.Entities.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("Id_Rol")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
