@Socios.Api_HostAddress = http://localhost:5056


###
### Get User Info (con Basic Auth)
### Usuario: CJR, Contraseña: 1234
### Base64: Q0pSOjEyMzQ=
###
GET {{Socios.Api_HostAddress}}/api/v1/me
Authorization: Basic Q0pSOjEyMzQ=
Accept: application/json


